### ISSUE TITLE
"Could not find Template::Mojo"

### ISSUE THREAD

**Issue by nbdsp** [tadzik/Template-Mojo#14]
When installing Task::Star with Panda, there is a warning during installation of Template::Mojo, and an error (pacage installation failure related to Mojo) during installing Bailador:

[user1 1427816697_1 ]$ panda install Template::Mojo
==> Fetching Template::Mojo
==> Building Template::Mojo
Compiling lib/Template/Mojo.pm to mbc
==> Testing Template::Mojo
t/00-basic.t ..... ok
t/01-template.t .. ok
t/02-complex.t ... ok
All tests successful.
Files=3, Tests=21, 15 wallclock secs ( 0.12 usr  0.01 sys + 12.84 cusr  0.50 csys = 13.47 CPU)
Result: PASS
==> Installing Template::Mojo
===WARNING!===
The distribution Template::Mojo does not seem to have a "provides" section in its META.info file,
and so the packages will not be installed in the correct location.
Please ask the author to add a "provides" section, mapping every exposed namespace to a
file location in the distribution.
See http://design.perl6.org/S22.html#provides for more information.

[user1 1427816697_1 ]$ panda install Bailador
==> Fetching Bailador
==> Building Bailador
Compiling lib/Bailador/Request.pm to mbc
Compiling lib/Bailador/Response.pm to mbc
Compiling lib/Bailador/Context.pm to mbc
Compiling lib/Bailador/Template.pm to mbc
Compiling lib/Bailador/Template/Mojo.pm to mbc
===SORRY!===
Could not find Template::Mojo in any of: /home/user1/.panda-work/1427816697_1/.panda-work/1427817064_1/blib/lib, /home/user1/.panda-work/1427816697_1/.panda-work/1427817064_1/lib, /home/user1/.perl6/2015.03-112-g01e1744/lib, /home/user1/.perl6/2015.03-112-g01e1744, /mnt/lib//perl6/rakudo/install/share/perl6/lib, /mnt/lib/perl6/rakudo/install/share/perl6/vendor/lib, /mnt/lib/perl6/rakudo/install/share/perl6/site/lib, /mnt/lib/perl6/rakudo/install/share/perl6, /mnt/lib/perl6/rakudo/install/share/perl6/vendor, /mnt/lib/perl6/rakudo/install/share/perl6/site
build stage failed for Bailador: Failed building lib/Bailador/Template/Mojo.pm
  in method install at lib/Panda.pm:122
  in method resolve at lib/Panda.pm:197
  in sub MAIN at /mnt/lib/perl6/panda/bin/panda:20
  in sub MAIN at /mnt/lib/perl6/panda/bin/panda:18
  in block <unit> at /mnt/lib/perl6/panda/bin/panda:82

Failure Summary
----------------
Bailador
	*build stage failed for Bailador: Failed building lib/Bailador/Template/Mojo.pm

**Comment by zoffixznet** [comment]
Same error:
```
==> Fetching Bailador
==> Building Bailador
Compiling lib/Bailador/Request.pm to mbc
Compiling lib/Bailador/Response.pm to mbc
Compiling lib/Bailador/Context.pm to mbc
Compiling lib/Bailador/Template.pm to mbc
Compiling lib/Bailador/Template/Mojo.pm to mbc
===SORRY!===
Could not find Template::Mojo in any of: /var/www/tmp/P6/.panda-work/1427818791_15/blib/lib, /var/www/tmp/P6/.panda-work/1427818791_15/lib, /home/zoffix/.perl6/2015.03-126-g5668f29/lib, /home/zoffix/.perl6/2015.03-126-g5668f29, /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/lib, /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/vendor/lib, /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/lib, /home/zoffix/.rakudobrew/moar-nom/install/share/perl6, /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/vendor, /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site
build stage failed for Bailador: Failed building lib/Bailador/Template/Mojo.pm
  in method install at lib/Panda.pm:122
  in block  at lib/Panda.pm:1
  in method resolve at lib/Panda.pm:187
  in sub MAIN at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/38:20
  in sub MAIN at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/38:18
  in block <unit> at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/38:82


Failure Summary
----------------
Task::Star
	*build stage failed for Bailador: Failed building lib/Bailador/Template/Mojo.pm
```

**Comment by zoffixznet** [comment]
Followup:
Installing with `panda install Template::Mojo` installs just fine. The issue seems to exist when using `panda install Task::Star`

**Comment by nbdsp** [comment]
@zoffixznet It installs, but there is a warning:

===WARNING!===
The distribution Template::Mojo does not seem to have a "provides" section in its META.info file,

( This warning is present in the output copied in the first post )

**Comment by zoffixznet** [comment]
@nbdsp that's fine. It's due to new feature in `panda`: (from [http://pl6anet.org/](http://pl6anet.org/))

> FROGGS has merged a panda branch called “eleven”, which makes use of the CompUnitRepo functionality of rakudo. The effect is that installed distributions will not be stored as files on disk, but go into a database like thing. This is done to be able to install (and locate) several same-named versions of a distributions, or distributions made by different authors. These can now coexist, though as a consequence every distribution must have a “provides” section [^1] in its META.info.
> Such a “provides” section (or an entire META.info) can be generated by running “panda gen-meta”. Modules without a proper “provides” have a panda icon with a strike-through “S11″ flag next to them on the modules list

This module simply hasn't been updated to have that section.

**Comment by zoffixznet** [comment]
Sent PR to address the missing `provides`: https://github.com/tadzik/Template-Mojo/pull/15

**Comment by tadzik** [comment]
Fixed now, thanks a lot :)
