### ISSUE TITLE
By-name parameters?

### ISSUE THREAD

**Issue by vendethiel** [tadzik/Template-Mojo#20]
The signature currently is: https://github.com/tadzik/Template-Mojo/blob/master/lib/Template/Mojo.pm#L126

Can we make it so that named parameters are allowed? I can probably whip up a PR.

**Comment by tadzik** [comment]
It'd be lovely; please whip up a PR if you can :)

**Comment by vendethiel** [comment]
Actually, I came back to using `template "foo", {params...}` and then ` % my (%v) = $^params` in the view (...i think) - works neatly. I looked at implementing this issue, but it seemed like there was a lot of flattening going on, and lost track of it.

**Comment by tadzik** [comment]
I wonder if the upcoming GLR changes will make us require more or less flattening here :)
