### ISSUE TITLE
No prevention of infinite loops ?

### ISSUE THREAD

**Issue by Emeric54** [tadzik/Template-Mojo#25]
I guess this is a problem. For example, I'm using a very simple template : 
```
% loop {
  I love Perl 6 !
% }
```
It'd be very cool to have a infinite loops prevention with Template-Mojo. What's your opinion ?

**Comment by vendethiel** [comment]
Why?

**Comment by Emeric54** [comment]
Infinite loops shouldn't be used in any template. I think it's just safer to don't allow them.

**Comment by vendethiel** [comment]
There are an infinite number of ways you can create an infinite loop if you want to. Why prevent people from writing code they want to?

**Comment by tadzik** [comment]
If you have an idea on how to solve the [halting problem](https://en.wikipedia.org/wiki/Halting_problem) within Template::Mojo, then I don't see why not :)

It is not possible to do in the general case, even if you do attempt to parse the code and look for clues like `loop` or `last` or whatnot. Implementing a half-solution would probably yield more false positives than anything else.
